homevork 30
soosanin2/homeworks pull request #18
Opened 2023-03-22 20:58 UTC by soosanin2

2023-03-25 18:48 UTC, klymenok requested changes

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +a = [google, facebook, twitter, amazon, apple]
Ви можете помістити значення прямо в list,  не обовʼязково для них створювати окремі змінні, якщо ви їх потім ніде не використовуєте

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +dict_location = list_location['results']
ваш код видає помилку, якщо міста, що ввів користувач, не існує

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +            + str(latitude) +  '&longitude='+ str(longitude) \
змінні latitude і longitude можуть бути не створені за певних обставин, код видає помилку при цьому

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +    if i['country_code'] != 'UA':
як отримати погоду в місті London?

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +        print(i['name'])
Навіщо користувачу ця інформація?

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +print(get_meteo_1.json())
В даних, що ви друкуєте, є багато інформації, але там немає головного – поточної температури

2023-03-25 18:48 UTC, klymenok commented on homevork_30/homevork_30.py
> +
Приберіть зайві пусті рядки в кінці файлу, залиште лише один

2023-03-26 15:15 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +a = [google, facebook, twitter, amazon, apple]
corrected

2023-03-26 15:15 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +        print(i['name'])
corrected

2023-03-26 15:15 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +print(get_meteo_1.json())
corrected

2023-03-26 15:15 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +
corrected

2023-03-26 17:08 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +dict_location = list_location['results']
corrected

2023-03-26 17:08 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +            + str(latitude) +  '&longitude='+ str(longitude) \
corrected

2023-03-26 17:08 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +    if i['country_code'] != 'UA':
corrected

2023-03-27 20:28 UTC, klymenok approved these changes
Looks good!

2023-03-27 21:22 UTC, merged