Homevork 031
soosanin2/homeworks pull request #19
Opened 2023-03-24 11:06 UTC by soosanin2

2023-03-25 19:24 UTC, klymenok requested changes
видаліть .idea з pull request, ця директорія не має відношення до домашнього завдання

2023-03-25 19:24 UTC, klymenok commented on homevork_30/homevork_30.py
> +import json
Цей файл не має бути в Pull Request. Для того, щоб такого не виникало - створюйте нові гілки з актуальної версії гілки `main`, а не з гілки попереднього домашнього завдання

2023-03-26 17:46 UTC, soosanin2 commented on homevork_30/homevork_30.py
> +import json
Не впевнений що я зрозумів все вірно.

https://github.com/soosanin2/homeworks/pull/20/files

Ви це мали на увазі ?

2023-03-29 07:39 UTC, closed without merging

2023-03-29 07:40 UTC, soosanin2 commented
це зайва гілка