Homevork 32
soosanin2/homeworks pull request #21
Opened 2023-03-28 17:10 UTC by soosanin2

2023-03-31 19:41 UTC, klymenok requested changes
Рекомендую також почати свторювати структуру проєкту і не тримати все в одному файлі

2023-03-31 19:41 UTC, klymenok commented on flaskProject/app.py
> +@app.get('/users/<string:title>')
Тут має бути /books, скоріше за все

2023-04-03 11:17 UTC, soosanin2 commented on flaskProject/app.py
> +@app.get('/users/<string:title>')
Так, я виправив

2023-04-06 18:40 UTC, klymenok approved these changes
Looks good!

2023-04-06 22:37 UTC, merged