homework_39
soosanin2/homeworks pull request #25
Opened 2023-04-19 14:47 UTC by soosanin2

створено новий проект

2023-04-21 17:01 UTC, klymenok requested changes

2023-04-21 17:01 UTC, klymenok commented on django39/robot/settings.py
> +SECRET_KEY = 'django-insecure-3*z$^b%ao^_*=@sbb3b-7zeckjrt@6h(d6!(pcd7!r5ww*+^(+'
Видаліть зайву змінну

2023-04-21 19:53 UTC, soosanin2 commented on django39/robot/settings.py
> +SECRET_KEY = 'django-insecure-3*z$^b%ao^_*=@sbb3b-7zeckjrt@6h(d6!(pcd7!r5ww*+^(+'
виправив

2023-04-23 11:12 UTC, klymenok approved these changes
Looks good!

2023-04-23 14:31 UTC, merged